### ISSUE TITLE
another Issue Daily Backup

### ISSUE THREAD

**Issue by jangt15** [extremenetworks/ExtremeScripting#115]
HI,

when I run the script dailybackup I receive the following error.

%% Unrecognized command:  ""
%% Invalid number detected.
Traceback (most recent call last):
  File "/usr/local/cfg/backup.py", line 117, in <module>
    if upmConfig() == None:
  File "/usr/local/cfg/backup.py", line 112, in upmConfig
    exosCmd(cmd)
  File "/usr/local/cfg/backup.py", line 42, in exosCmd
    result = exsh.clicmd(cmd, True)
RuntimeError

When I run the script a second time, it works without the error. But also there is no periodic UPM Timer.

Thanks
Jan

**Comment by stewilliams-extr** [comment]
You should be good now.  Please test it and let us know. 

Fixes made:  https://github.com/extremenetworks/ExtremeScripting/commit/40cad41a102b1d182ecb0970b534007cd2902054

```
* X440G2-24x-10G4.3 # load sc dailybackup.py
* X440G2-24x-10G4.4 # show upm profile
================================================================================
UPM Profile          Events                 Flags Ports
================================================================================
dailybackup          log-message(autologfilter e
dailybackup          UPM-Timer(dailybackup)    e
================================================================================
Number of UPM Profiles: 1
Number of UPM Events in Queue for execution: 0
Flags: d - disabled, e - enabled
Event name: log-message(Log filter name) - Truncated to 20 chars
* X440G2-24x-10G4.5 # show upm timers
Current Time: 2022-05-19 16:28:00
--------------------------------------------------------------------------------
UPM               Profile       Flags              Next Execution
Timer             Name                             time
--------------------------------------------------------------------------------
dailybackup      dailybackup    ep            2022-05-19 22:00:00(Every 86400 secs)
--------------------------------------------------------------------------------

Number of UPM Timers: 1
Flags: e - Profile is enabled, d: Profile is disabled
       o -Timer is non-periodic, p - Timer is periodic
* X440G2-24x-10G4.6 #

```
