### ISSUE TITLE
Issue with Onboard_Mgmt_VLAN-22.9.10.73v29.xwf

### ISSUE THREAD

**Issue by faekz0r** [extremenetworks/ExtremeScripting#146]
Our CSV is as follows:
```
serial number;mgmt vlanid;mgmt isid;mgmt ip;mgmt mask;mgmt gateway;sysname;site name
SB032210G-xxxxx;234;200234;10.113.234.151;255.255.255.0;10.113.234.1;LAB-5520-1;/World/bls-lab
```
But when we run the workflow (on demand), we get the following errors. Will paste the whole log.

```
Script Name: Onboard Mgmt VLAN_Move_to_VLAN_mgmt_IP
Date and Time: 2022-11-07T16:27:05.362
XIQ-SE User: priit
XIQ-SE User Domain: 
IP: 10.113.234.124
Workflow version 29 on XIQ-SE/XMC version 22.6.13.9
Activity: MoveToVlanMgmtIp
nbiQuery response = {network: {device={deviceData={serialNumber=SB032210G-xxxxx, macAddress=C8:BE:35:7C:5C:00}}}}
nbiQuery deviceData = {serialNumber: SB032210G-xxxxx, macAddress: C8:BE:35:7C:5C:00}
nbiQuery response = {network: {device={sitePath=/World/bls-lab, customVariables=[{globalAttribute=true, name=, scopeCategory=UNKNOWN, value=, valueType=UNKNOWN}]}}}
siteVariablesHash = {sitePath: /World/bls-lab, customVariables: [{globalAttribute=true, name=, scopeCategory=UNKNOWN, value=, valueType=UNKNOWN}]}
readSiteCustomVariables customVariables = {sitePath: /World/bls-lab, customVariables: [{globalAttribute=true, name=, scopeCategory=UNKNOWN, value=, valueType=UNKNOWN}]}
First pass, site local variables:
Second pass, parent site local variables:
-> /World
nbiQuery response = {network: {siteByLocation={customVariables=[{globalAttribute=true, name=, scopeCategory=UNKNOWN, value=, valueType=UNKNOWN}]}}}
siteVariablesHash = {customVariables: [{globalAttribute=true, name=, scopeCategory=UNKNOWN, value=, valueType=UNKNOWN}]}
Third pass, global variables:
readSiteCustomVariables siteVarDict = {'__PATH__': u'/World/bls-lab'}
readCsvToDict() csvVarDict =
{
    "__INDEX__": "serial number;mgmt vlanid;mgmt isid;mgmt ip;mgmt mask;mgmt gateway;sysname;site name", 
    "__PATH__": "/opt/extreme/mgmtdata.csv"
}
csvVarLookup csvVarsUsed = {u'mgmt vlanid': 1}
Traceback (most recent call last):
  File "<string>", line 1340, in <module>
  File "<string>", line 1039, in main
  File "<string>", line 944, in csvVarLookup
  File "<string>", line 323, in exitError
RuntimeError: csvVarLookup: the following variables were not found in the CSV file /opt/extreme/mgmtdata.csv for lookup SB032210G-xxxxx:
[u'mgmt vlanid']

Traceback (most recent call last):
  File "<string>", line 1340, in <module>
  File "<string>", line 1039, in main
  File "<string>", line 944, in csvVarLookup
  File "<string>", line 323, in exitError
RuntimeError: csvVarLookup: the following variables were not found in the CSV file /opt/extreme/mgmtdata.csv for lookup SB032210G-xxxxx:
[u'mgmt vlanid']
```

**Comment by faekz0r** [comment]
After reading the python script of the workflow, I discovered there's
`csv_reader = csv.reader(csv_file, delimiter=',')`

Since the guide does not explicitly say we have to use comma as a delimiter and an example in the guide had an excel picture of the CSV file, I assumed excel CSV formatting is fine. My bad.

**Comment by lgastevens** [comment]
Hi, thanks for reporting. The C in CSV stands for Comma!
But ok, I will change the workflow to take semi-colon as well.

**Comment by faekz0r** [comment]
> Hi, thanks for reporting. The C in CSV stands for Comma! But ok, I will change the workflow to take semi-colon as well.

Yeah, aware of the fact that CSV is originally (by RFC) comma only. But in the guide it shows an excel output of the CSV, so it seemed fair to assume that using excel formatting will be fine.

After a bit of research, it turns out excel delimiter choice is dependent on ones OS's Regional settings. For our Region the default List separator is a semicolon, not a comma. :-)
![image](https://user-images.githubusercontent.com/60139248/200569819-fc6e9f5c-1357-4648-b506-0ad88858b3b8.png)

**Comment by lgastevens** [comment]
This is the one I test with:

![image](https://user-images.githubusercontent.com/10697590/200663777-258a903a-da94-4b46-a328-42cf8012ad1a.png)

Note that you will also get that error message if you don't have an entry for SB032210G-xxxxx in your CSV file
